/**
 * Nova Context: Signal Map — OTED Assessment Platform
 * Vocabulary, schema, and query capabilities for the Signal Map domain.
 * Covers: OTED assessments, archetype scoring, lenses, seats, operator profiles.
 */

import type { NovaContext } from './finance';

export const SIGNAL_MAP_CONTEXT: NovaContext = {
  domain: 'signal-map',

  vocabulary: [
    'OTED — Operator and Team Execution Dynamics; the assessment framework Signal Map administers',
    'Signal Map — the standalone assessment platform deployed at localhost:3000 (separate from Delta Intelligence)',
    'Archetype — one of 14 operator pattern signatures; each subject receives a weighted portfolio (weights sum to 1.0)',
    'AT-01 Systems Cartographer — optimizes for clarity, boundary definition, structural coherence',
    'AT-02 Evidence Gatekeeper — optimizes for defensibility, auditability, truth under uncertainty',
    'AT-03 Mechanism Engineer — optimizes for installability, repeatable execution, measurable outcomes',
    'AT-04 Scenario Compiler — optimizes for scenario resilience, decision-grade tradeoffs',
    'AT-05 Compounding Librarian — optimizes for repeatability, scaling quality, institutional memory',
    'AT-06 Executive Synthesis Writer — optimizes for executive legibility, prioritization, actionability',
    'AT-07 Execution Driver — optimizes for speed, delivery reliability, close-the-loop discipline',
    'AT-08 Constraint-First Strategist — optimizes for safety, compliance, downside control',
    'AT-09 Opportunity Scout — optimizes for growth, value capture, strategic optionality',
    'AT-10 Commercial Synthesizer — optimizes for buy-in, external communication, adoption velocity',
    'AT-11 Interface Broker — optimizes for coordination efficiency, low rework, cross-team velocity',
    'AT-12 People Stabilizer — optimizes for retention, collaboration, team psychological safety',
    'AT-13 Learning Loop Optimizer — optimizes for continuous improvement, compounding returns',
    'AT-14 Decision Rights Architect — optimizes for decision velocity with integrity',
    'Hybrid classification — when top 2 archetypes each exceed 0.15 weight and jointly exceed 0.50; format: HYB-AT-XX+AT-YY',
    'Lens — one of 12 analytical frames applied to the archetype portfolio; each has overweights, underweights, and a dominant-failure mode',
    'L-01 Structural Integrity — evaluates coherent, inspectable operating model',
    'L-02 Evidence Quality — evaluates provenance-tracked, confidence-scored decisions',
    'L-03 Mechanism Installability — evaluates concrete installation path with owners and rollback',
    'L-04 Scenario Resilience — evaluates stress-testing against multiple futures',
    'L-05 Institutional Memory — evaluates template reuse, versioned playbooks, knowledge compounds',
    'L-06 Executive Legibility — evaluates decision-ready outputs actionable in under 5 minutes',
    'L-07 Execution Velocity — evaluates shipping cadence and close-the-loop discipline',
    'L-08 Risk Surface Coverage — evaluates failure mode enumeration and mitigation ownership',
    'L-09 Opportunity Capture — evaluates leverage-point identification and ROI-bounded action',
    'L-10 Stakeholder Alignment — evaluates structural truth translated into adoption-safe communication',
    'L-11 Interface Health — evaluates handoff quality, contract formality, rework rate at boundaries',
    'L-12 Learning Compounding — evaluates post-mortems, baseline tracking, playbook update cadence',
    'Seat — one of 10 C-suite / board organizational roles; profiles are overlaid against the subject\'s seat to identify fit, distortions, and guardrails',
    'Seat distortion — the characteristic over-index a role tends to produce (e.g., CEO gravitates toward narrative over structural truth)',
    'Pressure transform — behavioral shift pattern under uncertainty, time pressure, or political friction',
    'Failure pattern — known organizational dysfunction signature matched against archetype portfolio (e.g., TP-01 Missing Counterbalances)',
    'Install bundle — a structured intervention recommended based on matched failure patterns (e.g., IB-01 Delegated Throughput)',
    'Signal tag — atomic unit of scored evidence; format: SIG-AT::AT-XX with direction (raise/lower), weight, confidence',
    'Confidence score — bounded [0,1]; formula: 0.10 + 0.45*evidence_strength + 0.20*consistency + 0.15*recency + 0.10*scenario_relevance',
    'Evidence class — E0 (direct observation), E1 (inferred from behavior), E2 (self-reported), E3 (speculative)',
    'Access code — 6-character alphanumeric gate for assessment entry; single-use, status: active/used/expired/revoked',
    'Assessment session — one questionnaire attempt per person; 75 items across 7 blocks',
    'Profile — the complete scored output: archetype portfolio + lens profile + seat overlays + pressure transforms + failure matches + install bundles + narrative cache',
    'Narrative cache — the Claude-generated text stored on the profile row: operatingSignature, executiveSummary, deepDive, psychometricXref, roleFit, counterbalances, fullReport',
    'Operating signature — 30-50 word descriptor of how the subject operates; the headline of the profile',
    'Psychometric cross-reference — MBTI, DISC, Enneagram, Kolbe, StrengthsFinder, Big Five inferred from archetype weights (not independently measured)',
    'SJT — Situational Judgment Test; primary signal-capture block; 35 items (20 standard + 15 pressure variants)',
    'Forced choice — binary value-tradeoff items; subject picks between two operationally described behaviors',
    'Priority allocation — subject distributes 100 points across competing priorities',
    'Deterministic scoring — the scoring engine uses pure math, zero LLM calls; re-running always produces the same result',
    'Enrichment — the async Claude narrative generation phase that follows initial scoring',
  ],

  keyTables: [
    'persons — subject identity: id, name, email, org_context',
    'access_codes — assessment gates: id, code, person_id, status, expires_at',
    'assessment_sessions — questionnaire state: id, person_id, status (pending/in_progress/complete), responses (JSONB), current_item, consistency_score, started_at, completed_at',
    'evidence_items — analyst-tagged evidence (non-questionnaire): id, person_id, session_id, evidence_class (E0-E3), source_type, excerpt, signal_tags',
    'profiles — scored output: id, person_id, session_id, archetype_portfolio, lens_profile, seat_overlays, pressure_transforms, failure_modes, install_bundles, confidence, hybrid_classification, narrative_cache',
    'reports — PDF records: id, profile_id, tier (snapshot/profile/full), pdf_url, email_sent_to, email_sent_at',
  ],

  queryPatterns: [
    'How many OTED assessments have been completed?',
    'What are the top 3 archetypes for [person name]?',
    'What is the operating signature for the most recent completed profile?',
    'Which sessions are currently in progress?',
    'What failure patterns were matched in [person]\'s assessment?',
    'What install bundles are recommended for [person]?',
    'What is the confidence score for [session]?',
    'How many access codes are currently active vs used?',
    'Which profiles have had narrative enrichment completed?',
    'What is the hybrid classification for [person]?',
    'What does the Evidence Gatekeeper archetype mean?',
    'How is OTED confidence calculated?',
    'What are the 12 lenses and what does each measure?',
    'What is the distortion profile for a Chief Revenue Officer seat?',
  ],

  availableActions: [
    'Explain any of the 14 OTED archetypes in plain language',
    'Explain any of the 12 lenses and its failure mode',
    'Describe what a specific seat distortion means for a given role',
    'Interpret an archetype portfolio (top weights + hybrid classification)',
    'Explain the confidence score and what drives it up or down',
    'Describe what a failure pattern means and what install bundle addresses it',
    'Guide a user through what to expect from the assessment flow',
    'Explain the difference between deterministic scoring and Claude narrative enrichment',
    'Look up session or profile data in Supabase via the Signal Map API',
    'Describe the psychometric cross-reference methodology (derived, not independently measured)',
  ],

  gatewayEndpoints: [
    'Signal Map runs as a standalone Next.js app (localhost:3000) — not behind the Delta Intelligence gateway',
    'POST /api/session/start — validate access code, create session',
    'POST /api/session/save — save incremental responses',
    'POST /api/score — run deterministic scoring pipeline',
    'POST /api/score/enrich — run Claude narrative generation + PDF + Resend email (async, 300s)',
    'POST /api/report/generate — admin-only: render PDF for existing profile',
    'POST /api/admin/auth — admin login',
    'GET /api/admin/sessions — list all sessions (admin)',
    'GET /api/admin/codes — list/manage access codes (admin)',
  ],
};
